### ISSUE TITLE
As an Admin I want to view all invoices that have been registered in the system so I can get an overview of all invoices.

### ISSUE THREAD

**Issue by acerd44** [KYH-Net23/.github#14]
**Made by Hossén & Oliver**

## Acceptance Criteria
- [ ] Only admins should be able to access/view invoices.
- [ ] Admin should be able to click on a ‘All invoices’ button.
- [ ] On click, the Admin should be directed to the ‘All invoices’ page.
- [ ] The page should display a list of all the invoices that have been registered in the system with relevant and correct invoice information.
- [ ] There should be a button on each invoice that redirects to that specific invoice’s detailed page.
## Tasks
- [ ] Create an Invoice Data Model
- [ ] Create an Invoice View Model
- [ ] Implement API endpoint for fetching a list of invoices from a database.
- [ ] Implement a method for mapping the invoices received from the database to return a new list of invoice view model.
- [ ] Implement authorization so only admins can access and view invoices.
- [ ] Implement UI/frontend
   - [ ] Create a button that navigates to the "All Invoices" page.
   - [ ] Add a button to each invoice that redirects to that invoice's page which has more details.
   - [ ] Display all invoices in a table.
## Test Cases
- [ ] Verify that the list of invoices are loaded and displayed properly.
  - Prerequisites: 
    - User is logged in as an administrator.
    - At least one invoice is in the system
  - Steps
    - Navigate to the admin panel. 
    - Navigate to the "All Invoices" page.
  - Expected result: 
    - The system displays a list of all invoices in the system properly.
- [ ] Verify that only admins can access and view the invoices page.
  - Prerequisites:
    - The user attempting to access the page (presumably by URL) is not an administrator or is not logged in.
  - Steps:
      - Enter the URL for the admin panel's invoices page.
  - Expected results:
      - The user is redirected to a 401 error code page (unauthorized).
      - Display an error message.
- [ ] Verify that an error message is displayed when no invoices are fetched or found.
  - Prerequisites:
    - User is logged in as an administrator.
    - The system does not contain any invoices OR the API/microservice for fetching invoices is offline.
  - Steps:
    - Navigate to the admin panel.
    - Navigate to the "All Invoices" page.
  - Expected results:
    - The system displays an error message "No invoices found".
## Activity Diagram
![Image](https://i.imgur.com/6xKZ6Px.png)
